<?php 
/* Loads Et Line Font. */
add_filter( 'vc_iconpicker-type-etline', 'vc_iconpicker_type_etline' );

/**
 * Et Line icons 
 *
 * @param $icons - taken from filter - vc_map param field settings['source'] provided icons (default empty array).
 * If array categorized it will auto-enable category dropdown
 *
 * @since 4.4
 * @return array - of icons for iconpicker, can be categorized, or not.
 */
function vc_iconpicker_type_etline( $icons ) {

    $list_icons = array(
		array( "icon-mobile" => __( "Mobible", "js_composer" ) ),
		array( "icon-laptop" => __( "Laptop", "js_composer" ) ),
		array( "icon-desktop" => __( "Desktop", "js_composer" ) ),
		array( "icon-tablet" => __( "Tablet", "js_composer" ) ),
		array( "icon-phone" => __( "Phone", "js_composer" ) ),
		array( "icon-document" => __( "Document", "js_composer" ) ),
		array( "icon-documents" => __( "Documents", "js_composer" ) ),
		array( "icon-search" => __( "Search", "js_composer" ) ),
		array( "icon-clipboard" => __( "Clipboard", "js_composer" ) ),
		array( "icon-newspaper" => __( "Newspaper", "js_composer" ) ),
		array( "icon-notebook" => __( "Notebook", "js_composer" ) ),
		array( "icon-book-open" => __( "Book Open", "js_composer" ) ),
		array( "icon-browser" => __( "Browser", "js_composer" ) ),
		array( "icon-calendar" => __( "Calendar", "js_composer" ) ),
		array( "icon-presentation" => __( "Presentation", "js_composer" ) ),
		array( "icon-picture" => __( "Picture", "js_composer" ) ),
		array( "icon-pictures" => __( "Pictures", "js_composer" ) ),
		array( "icon-video" => __( "Video", "js_composer" ) ),
		array( "icon-camera" => __( "Camera", "js_composer" ) ),
		array( "icon-printer" => __( "Printer", "js_composer" ) ),
		array( "icon-toolbox" => __( "Toolbox", "js_composer" ) ),
		array( "icon-briefcase" => __( "Briefcase", "js_composer" ) ),
		array( "icon-wallet" => __( "Wallet", "js_composer" ) ),
		array( "icon-gift" => __( "Gift", "js_composer" ) ),
		array( "icon-bargraph" => __( "Bargraph", "js_composer" ) ),
		array( "icon-grid" => __( "Grid", "js_composer" ) ),
		array( "icon-expand" => __( "Expand", "js_composer" ) ),
		array( "icon-focus" => __( "Focus", "js_composer" ) ),
		array( "icon-edit" => __( "Edit", "js_composer" ) ),
		array( "icon-adjustments" => __( "Adjustments", "js_composer" ) ),
		array( "icon-ribbon" => __( "Ribbon", "js_composer" ) ),
		array( "icon-hourglass" => __( "Hourglass", "js_composer" ) ),
		array( "icon-lock" => __( "Lock", "js_composer" ) ),
		array( "icon-megaphone" => __( "Megaphone", "js_composer" ) ),
		array( "icon-shield" => __( "Shield", "js_composer" ) ),
		array( "icon-trophy" => __( "Trophy", "js_composer" ) ),
		array( "icon-flag" => __( "Flag", "js_composer" ) ),
		array( "icon-map" => __( "Map", "js_composer" ) ),
		array( "icon-puzzle" => __( "Puzzle", "js_composer" ) ),
		array( "icon-basket" => __( "Basket", "js_composer" ) ),
		array( "icon-envelope" => __( "Envelope", "js_composer" ) ),
		array( "icon-streetsign" => __( "Streetsign", "js_composer" ) ),
		array( "icon-telescope" => __( "Telescope", "js_composer" ) ),
		array( "icon-gears" => __( "Gears", "js_composer" ) ),
		array( "icon-key" => __( "Key", "js_composer" ) ),
		array( "icon-paperclip" => __( "Paperclip", "js_composer" ) ),
		array( "icon-attachment" => __( "Attachment", "js_composer" ) ),
		array( "icon-pricetags" => __( "Pricetags", "js_composer" ) ),
		array( "icon-lightbulb" => __( "Lightbulb", "js_composer" ) ),
		array( "icon-layers" => __( "Layers", "js_composer" ) ),
		array( "icon-pencil" => __( "Pencil", "js_composer" ) ),
		array( "icon-tools" => __( "Tools", "js_composer" ) ),
		array( "icon-tools-2" => __( "Tools 2", "js_composer" ) ),
		array( "icon-scissors" => __( "Scissors", "js_composer" ) ),
		array( "icon-paintbrush" => __( "Paintbrush", "js_composer" ) ),
		array( "icon-magnifying-glass" => __( "Magnifying Glass", "js_composer" ) ),
		array( "icon-circle-compass" => __( "Circle Compass", "js_composer" ) ),
		array( "icon-linegraph" => __( "Linegraph", "js_composer" ) ),
		array( "icon-mic" => __( "Mic", "js_composer" ) ),
		array( "icon-strategy" => __( "Strategy", "js_composer" ) ),
		array( "icon-beaker" => __( "Beaker", "js_composer" ) ),
		array( "icon-caution" => __( "Caution", "js_composer" ) ),
		array( "icon-recycle" => __( "Recycle", "js_composer" ) ),
		array( "icon-anchor" => __( "Anchor", "js_composer" ) ),
		array( "icon-profile-male" => __( "Profile Male", "js_composer" ) ),
		array( "icon-profile-female" => __( "Profile Female", "js_composer" ) ),
		array( "icon-bike" => __( "Bike", "js_composer" ) ),
		array( "icon-wine" => __( "Wine", "js_composer" ) ),
		array( "icon-hotairballoon" => __( "Hotairballoon", "js_composer" ) ),
		array( "icon-globe" => __( "Globe", "js_composer" ) ),
		array( "icon-genius" => __( "Genius", "js_composer" ) ),
		array( "icon-map-pin" => __( "Map Pin", "js_composer" ) ),
		array( "icon-dial" => __( "Dial", "js_composer" ) ),
		array( "icon-chat" => __( "Chat", "js_composer" ) ),
		array( "icon-heart" => __( "Heart", "js_composer" ) ),
		array( "icon-cloud" => __( "Cloud", "js_composer" ) ),
		array( "icon-upload" => __( "Upload", "js_composer" ) ),
		array( "icon-download" => __( "Download", "js_composer" ) ),
		array( "icon-target" => __( "Target", "js_composer" ) ),
		array( "icon-hazardous" => __( "Hazardous", "js_composer" ) ),
		array( "icon-piechart" => __( "Piechart", "js_composer" ) ),
		array( "icon-speedometer" => __( "Speedometer", "js_composer" ) ),
		array( "icon-global" => __( "Global", "js_composer" ) ),
		array( "icon-compass" => __( "Compass", "js_composer" ) ),
		array( "icon-lifesaver" => __( "Lifesaver", "js_composer" ) ),
		array( "icon-clock" => __( "Clock", "js_composer" ) ),
		array( "icon-aperture" => __( "Aperture", "js_composer" ) ),
		array( "icon-quote" => __( "Quote", "js_composer" ) ),
		array( "icon-scope" => __( "Scope", "js_composer" ) ),
		array( "icon-alarmclock" => __( "Alarmclock", "js_composer" ) ),
		array( "icon-refresh" => __( "Refresh", "js_composer" ) ),
		array( "icon-happy" => __( "Happy", "js_composer" ) ),
		array( "icon-sad" => __( "Sad", "js_composer" ) ),
		array( "icon-facebook" => __( "Facebook", "js_composer" ) ),
		array( "icon-twitter" => __( "Twitter", "js_composer" ) ),
		array( "icon-googleplus" => __( "Googleplus", "js_composer" ) ),
		array( "icon-rss" => __( "Rss", "js_composer" ) ),
		array( "icon-tumblr" => __( "Tumblr", "js_composer" ) ),
		array( "icon-linkedin" => __( "Linkedin", "js_composer" ) ),
		array( "icon-dribbble " => __( "Dribbble", "js_composer" ) ),
	);

	return array_merge( $icons, $list_icons );
}