<?php 
/* Loads Et Line Font. */
add_filter( 'vc_iconpicker-type-linearicons', 'vc_iconpicker_type_linearicons' );

/**
 * Et Line icons 
 *
 * @param $icons - taken from filter - vc_map param field settings['source'] provided icons (default empty array).
 * If array categorized it will auto-enable category dropdown
 *
 * @since 4.4
 * @return array - of icons for iconpicker, can be categorized, or not.
 */
function vc_iconpicker_type_linearicons( $icons ) {
	
	$list_icons = array(
		array( "lnr-home" => __( "Home", "cmstheme" ) ),
		array( "lnr-apartment" => __( "apartment", "js_composer" ) ),
		array( "lnr-pencil" => __( "pencil", "js_composer" ) ),
		array( "lnr-magic-wand" => __( "magic-wand", "js_composer" ) ),
		array( "lnr-drop" => __( "drop", "js_composer" ) ),
		array( "lnr-lighter" => __( "lighter", "js_composer" ) ),
		array( "lnr-poop" => __( "poop", "js_composer" ) ),
		array( "lnr-sun" => __( "sun", "js_composer" ) ),
		array( "lnr-moon" => __( "moon", "js_composer" ) ),
		array( "lnr-cloud" => __( "cloud", "js_composer" ) ),
		array( "lnr-cloud-upload" => __( "cloud-upload", "js_composer" ) ),
		array( "lnr-cloud-download" => __( "cloud-download", "js_composer" ) ),
		array( "lnr-cloud-sync" => __( "cloud-sync", "js_composer" ) ),
		array( "lnr-cloud-check" => __( "cloud-check", "js_composer" ) ),
		array( "lnr-database" => __( "database", "js_composer" ) ),
		array( "lnr-lock" => __( "lock", "js_composer" ) ),
		array( "lnr-cog" => __( "cog", "js_composer" ) ),
		array( "lnr-trash" => __( "trash", "js_composer" ) ),
		array( "lnr-dice" => __( "dice", "js_composer" ) ),
		array( "lnr-heart" => __( "heart", "js_composer" ) ),
		array( "lnr-star" => __( "star", "js_composer" ) ),
		array( "lnr-star-half" => __( "star-half", "js_composer" ) ),
		array( "lnr-star-empty" => __( "star-empty", "js_composer" ) ),
		array( "lnr-flag" => __( "flag", "js_composer" ) ),
		array( "lnr-envelope" => __( "envelope", "js_composer" ) ),
		array( "lnr-paperclip" => __( "paperclip", "js_composer" ) ),
		array( "lnr-inbox" => __( "inbox", "js_composer" ) ),
		array( "lnr-eye" => __( "eye", "js_composer" ) ),
		array( "lnr-printer" => __( "printer", "js_composer" ) ),
		array( "lnr-file-empty" => __( "file-empty", "js_composer" ) ),
		array( "lnr-file-add" => __( "file-add", "js_composer" ) ),
		array( "lnr-enter" => __( "enter", "js_composer" ) ),
		array( "lnr-exit" => __( "exit", "js_composer" ) ),
		array( "lnr-graduation-hat" => __( "graduation-hat", "js_composer" ) ),
		array( "lnr-license" => __( "license", "js_composer" ) ),
		array( "lnr-music-note" => __( "music-note", "js_composer" ) ),
		array( "lnr-film-play" => __( "film-play", "js_composer" ) ),
		array( "lnr-camera-video" => __( "camera-video", "js_composer" ) ),
		array( "lnr-camera" => __( "camera", "js_composer" ) ),
		array( "lnr-picture" => __( "picture", "js_composer" ) ),
		array( "lnr-book" => __( "book", "js_composer" ) ),
		array( "lnr-bookmark" => __( "bookmark", "js_composer" ) ),
		array( "lnr-user" => __( "user", "js_composer" ) ),
		array( "lnr-users" => __( "users", "js_composer" ) ),
		array( "lnr-shirt" => __( "shirt", "js_composer" ) ),
		array( "lnr-store" => __( "store", "js_composer" ) ),
		array( "lnr-cart" => __( "cart", "js_composer" ) ),
		array( "lnr-tag" => __( "tag", "js_composer" ) ),
		array( "lnr-phone-handset" => __( "phone-handset", "js_composer" ) ),
		array( "lnr-phone" => __( "phone", "js_composer" ) ),
		array( "lnr-pushpin" => __( "pushpin", "js_composer" ) ),
		array( "lnr-map-marker" => __( "map-marker", "js_composer" ) ),
		array( "lnr-map" => __( "map", "js_composer" ) ),
		array( "lnr-location" => __( "location", "js_composer" ) ),
		array( "lnr-calendar-full" => __( "calendar-full", "js_composer" ) ),
		array( "lnr-keyboard" => __( "keyboard", "js_composer" ) ),
		array( "lnr-spell-check" => __( "spell-check", "js_composer" ) ),
        array( "lnr-screen" => __( "screen", "js_composer" ) ),
        array( "lnr-smartphone" => __( "smartphone", "js_composer" ) ),
        array( "lnr-tablet" => __( "tablet", "js_composer" ) ),
        array( "lnr-laptop" => __( "laptop", "js_composer" ) ),
        array( "lnr-laptop-phone" => __( "laptop-phone", "js_composer" ) ),
        array( "lnr-power-switch" => __( "power-switch", "js_composer" ) ),
        array( "lnr-bubble" => __( "bubble", "js_composer" ) ),
        array( "lnr-heart-pulse" => __( "heart-pulse", "js_composer" ) ),
        array( "lnr-construction" => __( "construction", "js_composer" ) ),
        array( "lnr-pie-chart" => __( "pie-chart", "js_composer" ) ),
        array( "lnr-chart-bars" => __( "chart-bars", "js_composer" ) ),
        array( "lnr-gift" => __( "gift", "js_composer" ) ),
        array( "lnr-diamond" => __( "diamond", "js_composer" ) ),
        array( "lnr-linearicons" => __( "linearicons", "js_composer" ) ),
        array( "lnr-dinner" => __( "dinner", "js_composer" ) ),
        array( "lnr-coffee-cup" => __( "coffee-cup", "js_composer" ) ),
        array( "lnr-leaf" => __( "leaf", "js_composer" ) ),
        array( "lnr-paw" => __( "paw", "js_composer" ) ),
        array( "lnr-rocket" => __( "rocket", "js_composer" ) ),
        array( "lnr-briefcase" => __( "briefcase", "js_composer" ) ),
        array( "lnr-bus" => __( "bus", "js_composer" ) ),
        array( "lnr-car" => __( "car", "js_composer" ) ),
        array( "lnr-train" => __( "train", "js_composer" ) ),
        array( "lnr-bicycle" => __( "bicycle", "js_composer" ) ),
        array( "lnr-wheelchair" => __( "wheelchair", "js_composer" ) ),
        array( "lnr-select" => __( "select", "js_composer" ) ),
        array( "lnr-earth" => __( "earth", "js_composer" ) ),
        array( "lnr-smile" => __( "smile", "js_composer" ) ),
        array( "lnr-sad" => __( "sad", "js_composer" ) ),
        array( "lnr-neutral" => __( "neutral", "js_composer" ) ),
        array( "lnr-mustache" => __( "mustache", "js_composer" ) ),
        array( "lnr-alarm" => __( "alarm", "js_composer" ) ),
        array( "lnr-bullhorn" => __( "bullhorn", "js_composer" ) ),
        array( "lnr-volume-high" => __( "volume-high", "js_composer" ) ),
        array( "lnr-volume-medium" => __( "volume-medium", "js_composer" ) ),
        array( "lnr-volume-low" => __( "volume-low", "js_composer" ) ),
        array( "lnr-volume" => __( "volume", "js_composer" ) ),
        array( "lnr-mic" => __( "mic", "js_composer" ) ),
        array( "lnr-hourglass" => __( "hourglass", "js_composer" ) ),
        array( "lnr-undo" => __( "undo", "js_composer" ) ),
        array( "lnr-redo" => __( "redo", "js_composer" ) ),
        array( "lnr-sync" => __( "sync", "js_composer" ) ),
        array( "lnr-history" => __( "history", "js_composer" ) ),
        array( "lnr-clock" => __( "clock", "js_composer" ) ),
        array( "lnr-download" => __( "download", "js_composer" ) ),
        array( "lnr-enter-down" => __( "enter-down", "js_composer" ) ),
        array( "lnr-exit-up" => __( "exit-up", "js_composer" ) ),
        array( "lnr-upload" => __( "upload", "js_composer" ) ),
        array( "lnr-bug" => __( "bug", "js_composer" ) ),
        array( "lnr-code" => __( "code", "js_composer" ) ),
        array( "lnr-link" => __( "link", "js_composer" ) ),
        array( "lnr-unlink" => __( "unlink", "js_composer" ) ),
        array( "lnr-thumbs-up" => __( "thumbs-up", "js_composer" ) ),
        array( "lnr-thumbs-down" => __( "thumbs-down", "js_composer" ) ),
        array( "lnr-magnifier" => __( "magnifier", "js_composer" ) ),
        array( "lnr-cross" => __( "cross", "js_composer" ) ),
        array( "lnr-menu" => __( "menu", "js_composer" ) ),
        array( "lnr-list" => __( "list", "js_composer" ) ),
        array( "lnr-chevron-up" => __( "chevron-up", "js_composer" ) ),
        array( "lnr-chevron-down" => __( "chevron-down", "js_composer" ) ),
        array( "lnr-chevron-left" => __( "chevron-left", "js_composer" ) ),
        array( "lnr-chevron-right" => __( "chevron-right", "js_composer" ) ),
        array( "lnr-arrow-up" => __( "arrow-up", "js_composer" ) ),
        array( "lnr-arrow-down" => __( "arrow-down", "js_composer" ) ),
        array( "lnr-arrow-left" => __( "arrow-left", "js_composer" ) ),
        array( "lnr-arrow-right" => __( "arrow-right", "js_composer" ) ),
        array( "lnr-move" => __( "move", "js_composer" ) ),
        array( "lnr-warning" => __( "warning", "js_composer" ) ),
        array( "lnr-question-circle" => __( "question-circle", "js_composer" ) ),
        array( "lnr-menu-circle" => __( "menu-circle", "js_composer" ) ),
        array( "lnr-checkmark-circle" => __( "checkmark-circle", "js_composer" ) ),
        array( "lnr-cross-circle" => __( "cross-circle", "js_composer" ) ),
        array( "lnr-plus-circle" => __( "plus-circle", "js_composer" ) ),
        array( "lnr-circle-minus" => __( "circle-minus", "js_composer" ) ),
        array( "lnr-arrow-up-circle" => __( "arrow-up-circle", "js_composer" ) ),
        array( "lnr-arrow-down-circle" => __( "arrow-down-circle", "js_composer" ) ),
        array( "lnr-arrow-left-circle" => __( "arrow-left-circle", "js_composer" ) ),
        array( "lnr-arrow-right-circle" => __( "chevron-right-circle", "js_composer" ) ),
        array( "lnr-chevron-up-circle" => __( "chevron-up-circle", "js_composer" ) ),
        array( "lnr-chevron-down-circle" => __( "chevron-down-circle", "js_composer" ) ),
        array( "lnr-chevron-left-circle" => __( "chevron-left-circle", "js_composer" ) ),
        array( "lnr-chevron-right-circle" => __( "chevron-right-circle", "js_composer" ) ),
        array( "lnr-crop" => __( "crop", "js_composer" ) ),
        array( "lnr-frame-expand" => __( "frame-expand", "js_composer" ) ),
        array( "lnr-frame-contract" => __( "frame-contract", "js_composer" ) ),
        array( "lnr-layers" => __( "layers", "js_composer" ) ),
        array( "lnr-funnel" => __( "funnel", "js_composer" ) ),
        array( "lnr-text-format" => __( "text-format", "js_composer" ) ),
        array( "lnr-text-format-remove" => __( "text-format-remove", "js_composer" ) ),
        array( "lnr-text-size" => __( "text-size", "js_composer" ) ),
        array( "lnr-bold" => __( "bold", "js_composer" ) ),
        array( "lnr-italic" => __( "italic", "js_composer" ) ),
        array( "lnr-underline" => __( "underline", "js_composer" ) ),
        array( "lnr-strikethrough" => __( "strikethrough", "js_composer" ) ),
        array( "lnr-highlight" => __( "highlight", "js_composer" ) ),
        array( "lnr-text-align-left" => __( "text-align-left", "js_composer" ) ),
        array( "lnr-text-align-center" => __( "text-align-center", "js_composer" ) ),
        array( "lnr-text-align-right" => __( "text-align-right", "js_composer" ) ),
        array( "lnr-text-align-justify" => __( "text-align-justify", "js_composer" ) ),
        array( "lnr-line-spacing" => __( "line-spacing", "js_composer" ) ),
        array( "lnr-indent-increase" => __( "indent-increase", "js_composer" ) ),
        array( "lnr-indent-decrease" => __( "indent-decrease", "js_composer" ) ),
        array( "lnr-pilcrow" => __( "pilcrow", "js_composer" ) ),
        array( "lnr-direction-ltr" => __( "direction-ltr", "js_composer" ) ),
        array( "lnr-direction-rtl" => __( "direction-rtl", "js_composer" ) ),
        array( "lnr-page-break" => __( "page-break", "js_composer" ) ),
        array( "lnr-sort-alpha-asc" => __( "sort-alpha-asc", "js_composer" ) ),
        array( "lnr-sort-amount-asc" => __( "sort-amount-asc", "js_composer" ) ),
        array( "lnr-hand" => __( "hand", "js_composer" ) ),
        array( "lnr-pointer-up" => __( "pointer-up", "js_composer" ) ),
        array( "lnr-pointer-right" => __( "pointer-right", "js_composer" ) ),
        array( "lnr-pointer-down" => __( "pointer-down", "js_composer" ) ),
        array( "lnr-pointer-left" => __( "pointer-left", "js_composer" ) ),
    );

	return array_merge( $icons, $list_icons );
}